# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import hfedchain_pb2 as proto_dot_hfedchain__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/hfedchain_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FogConsensusStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ConsensusStream = channel.stream_stream(
                '/hfedchain.FogConsensus/ConsensusStream',
                request_serializer=proto_dot_hfedchain__pb2.ConsensusMessage.SerializeToString,
                response_deserializer=proto_dot_hfedchain__pb2.ConsensusMessage.FromString,
                _registered_method=True)


class FogConsensusServicer:
    """Missing associated documentation comment in .proto file."""

    def ConsensusStream(self, request_iterator, context):
        """Bidirectional streaming for HotStuff consensus messages
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FogConsensusServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ConsensusStream': grpc.stream_stream_rpc_method_handler(
                    servicer.ConsensusStream,
                    request_deserializer=proto_dot_hfedchain__pb2.ConsensusMessage.FromString,
                    response_serializer=proto_dot_hfedchain__pb2.ConsensusMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hfedchain.FogConsensus', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hfedchain.FogConsensus', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FogConsensus:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ConsensusStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/hfedchain.FogConsensus/ConsensusStream',
            proto_dot_hfedchain__pb2.ConsensusMessage.SerializeToString,
            proto_dot_hfedchain__pb2.ConsensusMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class CloudAggregationStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitClusterOutput = channel.unary_unary(
                '/hfedchain.CloudAggregation/SubmitClusterOutput',
                request_serializer=proto_dot_hfedchain__pb2.ClusterOutput.SerializeToString,
                response_deserializer=proto_dot_hfedchain__pb2.GlobalOutputMessage.FromString,
                _registered_method=True)


class CloudAggregationServicer:
    """Missing associated documentation comment in .proto file."""

    def SubmitClusterOutput(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CloudAggregationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubmitClusterOutput': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitClusterOutput,
                    request_deserializer=proto_dot_hfedchain__pb2.ClusterOutput.FromString,
                    response_serializer=proto_dot_hfedchain__pb2.GlobalOutputMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hfedchain.CloudAggregation', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hfedchain.CloudAggregation', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CloudAggregation:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SubmitClusterOutput(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hfedchain.CloudAggregation/SubmitClusterOutput',
            proto_dot_hfedchain__pb2.ClusterOutput.SerializeToString,
            proto_dot_hfedchain__pb2.GlobalOutputMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ModelServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetModel = channel.unary_unary(
                '/hfedchain.ModelService/GetModel',
                request_serializer=proto_dot_hfedchain__pb2.Empty.SerializeToString,
                response_deserializer=proto_dot_hfedchain__pb2.ModelDistribution.FromString,
                _registered_method=True)
        self.PushModel = channel.unary_unary(
                '/hfedchain.ModelService/PushModel',
                request_serializer=proto_dot_hfedchain__pb2.ModelDistribution.SerializeToString,
                response_deserializer=proto_dot_hfedchain__pb2.Empty.FromString,
                _registered_method=True)


class ModelServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def GetModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PushModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ModelServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetModel': grpc.unary_unary_rpc_method_handler(
                    servicer.GetModel,
                    request_deserializer=proto_dot_hfedchain__pb2.Empty.FromString,
                    response_serializer=proto_dot_hfedchain__pb2.ModelDistribution.SerializeToString,
            ),
            'PushModel': grpc.unary_unary_rpc_method_handler(
                    servicer.PushModel,
                    request_deserializer=proto_dot_hfedchain__pb2.ModelDistribution.FromString,
                    response_serializer=proto_dot_hfedchain__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hfedchain.ModelService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hfedchain.ModelService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ModelService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hfedchain.ModelService/GetModel',
            proto_dot_hfedchain__pb2.Empty.SerializeToString,
            proto_dot_hfedchain__pb2.ModelDistribution.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PushModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hfedchain.ModelService/PushModel',
            proto_dot_hfedchain__pb2.ModelDistribution.SerializeToString,
            proto_dot_hfedchain__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
